name: Hello World - Learning Pathway
on:
  push:
    paths:
      - 'actions-learning-pathway/**'   # sub project course in this repo
jobs: 
  hello-world-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "$(cat actions-learning-pathway/hello_world.txt)"