name: Hello World - Learning Pathway
on:
  push:
    paths:
      - 'actions-learning-pathway/**'   # sub project course in this repo

permissions:
  contents: read
  
jobs: 
  hello-world-job:
    runs-on: ubuntu-latest
    env:
      COURSE_PATH: actions-learning-pathway
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "$(cat $COURSE_PATH/hello_world.txt)"
